# Tests for namespace.R

# Create mock blocks
blocks <- list(
  list(
    lines = c("Function A", "@export"),
    object = "func_a",
    type = "function",
    formals = NULL,
    file = "test.R",
    line = 1
  ),
  list(
    lines = c("Function B", "@export", "@importFrom stats lm"),
    object = "func_b",
    type = "function",
    formals = NULL,
    file = "test.R",
    line = 10
  ),
  list(
    lines = c("Internal", "@keywords internal"),
    object = "internal_fn",
    type = "function",
    formals = NULL,
    file = "test.R",
    line = 20
  )
)

# Test generate_namespace
ns <- rhydrogen:::generate_namespace(blocks)

# Check header
expect_true(grepl("Generated by rhydrogen", ns))

# Check exports
expect_true(grepl("export\\(func_a\\)", ns))
expect_true(grepl("export\\(func_b\\)", ns))

# Internal function should NOT be exported
expect_false(grepl("export\\(internal_fn\\)", ns))

# Check importFrom
expect_true(grepl("importFrom\\(stats,lm\\)", ns))

# Test S3 method
blocks_s3 <- list(
  list(
    lines = c("Print method", "@export", "@exportS3Method print myclass"),
    object = "print.myclass",
    type = "function",
    formals = c("x", "..."),
    file = "test.R",
    line = 1
  )
)

ns_s3 <- rhydrogen:::generate_namespace(blocks_s3)
expect_true(grepl("S3method\\(print,myclass\\)", ns_s3))
expect_true(grepl("export\\(print.myclass\\)", ns_s3))
