#' Generate NAMESPACE Content
#'
#' @param blocks List of documentation blocks from parse_package().
#' @return Character string of NAMESPACE content.
#' @keywords internal
generate_namespace <- function(blocks) {
  exports <- character()
  s3methods <- list()
  imports <- character()
  import_froms <- list()
  use_dynlibs <- character()

  for (block in blocks) {
    tags <- parse_tags(
      block$lines,
      block$object,
      block$file,
      block$line
    )

    # Exports
    if (tags$export) {
      exports <- c(exports, block$object)
    }

    # S3 methods
    if (!is.null(tags$exportS3Method)) {
      s3m <- tags$exportS3Method
      if (!is.null(s3m$generic) && !is.null(s3m$class)) {
        s3methods <- c(s3methods, list(list(
          generic = s3m$generic,
          class = s3m$class
        )))
      } else if (!is.null(s3m$explicit)) {
        # Try to parse from function name: generic.class
        parts <- strsplit(block$object, "\\.")[[1]]
        if (length(parts) >= 2) {
          s3methods <- c(s3methods, list(list(
            generic = parts[1],
            class = paste(parts[-1], collapse = ".")
          )))
        }
      }
    }

    # Imports
    for (imp in tags$imports) {
      imports <- c(imports, imp)
    }

    # ImportFrom
    for (impf in tags$importFroms) {
      import_froms <- c(import_froms, list(impf))
    }

    # useDynLib
    if (!is.null(tags$useDynLib)) {
      use_dynlibs <- c(use_dynlibs, tags$useDynLib)
    }
  }

  # Build NAMESPACE content
  lines <- character()
  lines <- c(lines, "# Generated by rhydrogen: do not edit by hand")
  lines <- c(lines, "")

  # Exports (sorted)
  exports <- sort(unique(exports))
  for (exp in exports) {
    lines <- c(lines, paste0("export(", exp, ")"))
  }

  # S3 methods (sorted by generic, then class)
  if (length(s3methods) > 0) {
    if (length(exports) > 0) lines <- c(lines, "")
    s3methods <- s3methods[order(
      vapply(s3methods, function(x) paste(x$generic, x$class), character(1))
    )]
    for (s3m in s3methods) {
      lines <- c(lines, paste0("S3method(", s3m$generic, ",", s3m$class, ")"))
    }
  }

  # Imports (sorted)
  imports <- sort(unique(imports))
  if (length(imports) > 0) {
    lines <- c(lines, "")
    for (imp in imports) {
      lines <- c(lines, paste0("import(", imp, ")"))
    }
  }

  # ImportFrom (sorted by package, then symbol)
  if (length(import_froms) > 0) {
    # Merge by package
    by_pkg <- list()
    for (impf in import_froms) {
      if (is.null(by_pkg[[impf$pkg]])) {
        by_pkg[[impf$pkg]] <- character()
      }
      by_pkg[[impf$pkg]] <- c(by_pkg[[impf$pkg]], impf$symbols)
    }

    if (length(imports) == 0) lines <- c(lines, "")
    for (pkg in sort(names(by_pkg))) {
      syms <- sort(unique(by_pkg[[pkg]]))
      for (sym in syms) {
        lines <- c(lines, paste0("importFrom(", pkg, ",", sym, ")"))
      }
    }
  }

  # useDynLib (sorted)
  use_dynlibs <- sort(unique(use_dynlibs))
  if (length(use_dynlibs) > 0) {
    lines <- c(lines, "")
    for (udl in use_dynlibs) {
      lines <- c(lines, paste0("useDynLib(", udl, ")"))
    }
  }

  paste(lines, collapse = "\n")
}

#' Write NAMESPACE File
#'
#' @param content NAMESPACE content string.
#' @param path Package root path.
#' @param mode Either "overwrite" or "append".
#' @keywords internal
write_namespace <- function(content, path = ".", mode = "overwrite") {
  filepath <- file.path(path, "NAMESPACE")

  if (mode == "overwrite") {
    writeLines(content, filepath, useBytes = TRUE)
  } else if (mode == "append") {
    # Append between markers
    start_marker <- "## rhydrogen start"
    end_marker <- "## rhydrogen end"

    if (file.exists(filepath)) {
      existing <- readLines(filepath, warn = FALSE)

      # Find marker positions
      start_pos <- grep(paste0("^", start_marker), existing)
      end_pos <- grep(paste0("^", end_marker), existing)

      if (length(start_pos) > 0 && length(end_pos) > 0) {
        # Replace between markers
        before <- if (start_pos[1] > 1) existing[1:(start_pos[1] - 1)] else character()
        after <- if (end_pos[1] < length(existing)) existing[(end_pos[1] + 1):length(existing)] else character()

        new_content <- c(
          before,
          start_marker,
          strsplit(content, "\n")[[1]],
          end_marker,
          after
        )
      } else {
        # No markers - append at end
        new_content <- c(
          existing,
          "",
          start_marker,
          strsplit(content, "\n")[[1]],
          end_marker
        )
      }
    } else {
      # New file
      new_content <- c(
        start_marker,
        strsplit(content, "\n")[[1]],
        end_marker
      )
    }

    writeLines(new_content, filepath, useBytes = TRUE)
  }

  filepath
}
